-- ============================================================
-- MCP Financial Server — Seed Data (auto-generated)
-- Run AFTER schema.sql in Supabase SQL Editor
-- ============================================================

-- Companies
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('AAPL', 'Apple Inc.', 'Technology', 'Consumer Electronics', 3400000000000, 'Tim Cook', 'Cupertino, CA', 1976, 164000, 'https://apple.com', 'Designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('MSFT', 'Microsoft Corporation', 'Technology', 'Software Infrastructure', 3100000000000, 'Satya Nadella', 'Redmond, WA', 1975, 228000, 'https://microsoft.com', 'Develops and licenses software, services, devices, and solutions worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('GOOGL', 'Alphabet Inc.', 'Technology', 'Internet Content & Information', 2100000000000, 'Sundar Pichai', 'Mountain View, CA', 1998, 182000, 'https://abc.xyz', 'Provides online advertising services, search, cloud computing, and technology products.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('NVDA', 'NVIDIA Corporation', 'Technology', 'Semiconductors', 2800000000000, 'Jensen Huang', 'Santa Clara, CA', 1993, 29600, 'https://nvidia.com', 'Designs and sells graphics processing units and system-on-chip units.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('META', 'Meta Platforms Inc.', 'Technology', 'Internet Content & Information', 1500000000000, 'Mark Zuckerberg', 'Menlo Park, CA', 2004, 67317, 'https://meta.com', 'Builds technologies that help people connect, find communities, and grow businesses.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('JNJ', 'Johnson & Johnson', 'Healthcare', 'Drug Manufacturers', 380000000000, 'Joaquin Duato', 'New Brunswick, NJ', 1886, 131900, 'https://jnj.com', 'Researches, develops, manufactures, and sells healthcare products worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('UNH', 'UnitedHealth Group', 'Healthcare', 'Healthcare Plans', 480000000000, 'Andrew Witty', 'Minnetonka, MN', 1977, 400000, 'https://unitedhealthgroup.com', 'Operates as a diversified healthcare company offering health benefits and services.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('PFE', 'Pfizer Inc.', 'Healthcare', 'Drug Manufacturers', 160000000000, 'Albert Bourla', 'New York, NY', 1849, 88000, 'https://pfizer.com', 'Discovers, develops, and manufactures healthcare products worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('ABBV', 'AbbVie Inc.', 'Healthcare', 'Drug Manufacturers', 310000000000, 'Robert Michael', 'North Chicago, IL', 2013, 50000, 'https://abbvie.com', 'Discovers, develops, and commercializes pharmaceuticals worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('TMO', 'Thermo Fisher Scientific', 'Healthcare', 'Diagnostics & Research', 200000000000, 'Marc Casper', 'Waltham, MA', 2006, 130000, 'https://thermofisher.com', 'Provides life sciences solutions, analytical instruments, and laboratory products.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('JPM', 'JPMorgan Chase & Co.', 'Financial Services', 'Banks - Diversified', 590000000000, 'Jamie Dimon', 'New York, NY', 2000, 309926, 'https://jpmorganchase.com', 'Provides global financial services including investment banking, treasury, and securities.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('V', 'Visa Inc.', 'Financial Services', 'Credit Services', 560000000000, 'Ryan McInerney', 'San Francisco, CA', 1958, 30800, 'https://visa.com', 'Operates as a payments technology company worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('MA', 'Mastercard Inc.', 'Financial Services', 'Credit Services', 430000000000, 'Michael Miebach', 'Purchase, NY', 1966, 33400, 'https://mastercard.com', 'Provides payment processing and technology-based payment solutions.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('BAC', 'Bank of America Corp.', 'Financial Services', 'Banks - Diversified', 330000000000, 'Brian Moynihan', 'Charlotte, NC', 1998, 213000, 'https://bankofamerica.com', 'Provides banking and financial products and services for individual consumers and businesses.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('GS', 'Goldman Sachs Group', 'Financial Services', 'Capital Markets', 160000000000, 'David Solomon', 'New York, NY', 1869, 45300, 'https://goldmansachs.com', 'Provides investment banking, securities, and investment management services.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('AMZN', 'Amazon.com Inc.', 'Consumer Discretionary', 'Internet Retail', 1900000000000, 'Andy Jassy', 'Seattle, WA', 1994, 1541000, 'https://amazon.com', 'Engages in the retail sale of consumer products and subscriptions through online and physical stores.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('TSLA', 'Tesla Inc.', 'Consumer Discretionary', 'Auto Manufacturers', 780000000000, 'Elon Musk', 'Austin, TX', 2003, 140473, 'https://tesla.com', 'Designs, develops, manufactures, and sells electric vehicles and energy solutions.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('NKE', 'Nike Inc.', 'Consumer Discretionary', 'Footwear & Accessories', 120000000000, 'John Donahoe', 'Beaverton, OR', 1964, 79400, 'https://nike.com', 'Designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('SBUX', 'Starbucks Corporation', 'Consumer Discretionary', 'Restaurants', 105000000000, 'Laxman Narasimhan', 'Seattle, WA', 1971, 381000, 'https://starbucks.com', 'Operates as a roaster, marketer, and retailer of specialty coffee worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('HD', 'The Home Depot Inc.', 'Consumer Discretionary', 'Home Improvement Retail', 350000000000, 'Ted Decker', 'Atlanta, GA', 1978, 465000, 'https://homedepot.com', 'Operates as a home improvement retailer selling building materials, home improvement products, and lawn and garden products.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('XOM', 'Exxon Mobil Corporation', 'Energy', 'Oil & Gas Integrated', 460000000000, 'Darren Woods', 'Irving, TX', 1999, 62000, 'https://exxonmobil.com', 'Explores, produces, transports, and sells crude oil, natural gas, and petroleum products.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('CVX', 'Chevron Corporation', 'Energy', 'Oil & Gas Integrated', 290000000000, 'Mike Wirth', 'San Ramon, CA', 1879, 43846, 'https://chevron.com', 'Engages in integrated energy and chemicals operations worldwide.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('COP', 'ConocoPhillips', 'Energy', 'Oil & Gas E&P', 130000000000, 'Ryan Lance', 'Houston, TX', 2002, 10100, 'https://conocophillips.com', 'Explores for, produces, transports, and markets crude oil, natural gas, and related products.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('NEE', 'NextEra Energy Inc.', 'Energy', 'Utilities - Regulated Electric', 150000000000, 'John Ketchum', 'Juno Beach, FL', 1925, 16800, 'https://nexteraenergy.com', 'Generates, transmits, distributes, and sells electric power in North America.') ON CONFLICT (ticker) DO NOTHING;
INSERT INTO companies (ticker, name, sector, industry, market_cap, ceo, headquarters, founded_year, employees, website, description) VALUES ('SLB', 'Schlumberger Limited', 'Energy', 'Oil & Gas Equipment & Services', 65000000000, 'Olivier Le Peuch', 'Houston, TX', 1926, 99000, 'https://slb.com', 'Provides technology and services for the energy industry worldwide.') ON CONFLICT (ticker) DO NOTHING;

-- Financial Reports (sample: first 10)
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2022, 1, 55631219101, 1995418928, 3.74, 0.0588, 2.236, 10310684445, '2022-03-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2022, 2, 116846326096, 6282710776, 0.93, 0.0804, 0.734, 17652098062, '2022-06-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2022, 3, 113128415155, 10282294993, 8.4, 0.1196, 0.739, 18988959342, '2022-09-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2022, 4, 64935803837, 12156261105, 2.75, 0.2943, 2.876, 7618197662, '2022-12-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2023, 1, 91937947921, 6471687841, 9.25, 0.0839, 2.441, 18014905996, '2023-03-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2023, 2, 55187984005, 14042152676, 8.5, 0.3906, 2.505, 9586370840, '2023-06-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2023, 3, 90945643201, 17925297508, 1.16, 0.2521, 0.761, 9810997056, '2023-09-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2023, 4, 91973405392, 10218661744, 5.79, 0.1473, 1.174, 8452485284, '2023-12-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2024, 1, 51373225387, 7686332361, 11.07, 0.2632, 0.574, 6467431256, '2024-03-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;
INSERT INTO financial_reports (company_id, fiscal_year, fiscal_quarter, revenue, net_income, eps, operating_margin, debt_to_equity, free_cash_flow, report_date) VALUES (1, 2024, 2, 72456852025, 17566146945, 11.75, 0.2896, 0.764, 4088019125, '2024-06-28') ON CONFLICT (company_id, fiscal_year, fiscal_quarter) DO NOTHING;

-- Stock Prices (sample: first 10)
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-01', 417.18, 414.01, 419.21, 411.1, 7099943) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-02', 423.84, 423.05, 426.1, 411.21, 64920305) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-03', 412.75, 413.56, 414.16, 410.34, 36452485) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-04', 409.32, 407.08, 413.67, 404.08, 23808678) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-07', 399.77, 401.23, 411.05, 398.0, 48038943) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-08', 405.18, 401.28, 404.13, 399.79, 74961132) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-09', 405.64, 402.59, 403.32, 401.97, 28505978) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-10', 408.78, 408.81, 416.49, 401.79, 51226575) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-11', 418.56, 419.26, 429.15, 410.7, 25027648) ON CONFLICT (company_id, price_date) DO NOTHING;
INSERT INTO stock_prices (company_id, price_date, open_price, close_price, high_price, low_price, volume) VALUES (1, '2024-10-14', 415.75, 415.43, 419.17, 405.26, 37342202) ON CONFLICT (company_id, price_date) DO NOTHING;

-- Analyst Ratings (sample: first 10)
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (1, 'Christopher Harvey', 'Wells Fargo', 'Buy', 359.53, '2024-11-14', 'Buy rating for AAPL based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (1, 'Venu Krishna', 'Barclays', 'Hold', 351.46, '2024-10-05', 'Hold rating for AAPL based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (2, 'Venu Krishna', 'Barclays', 'Buy', 342.79, '2024-10-02', 'Buy rating for MSFT based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (2, 'Christopher Harvey', 'Wells Fargo', 'Strong Sell', 284.37, '2024-12-04', 'Strong Sell rating for MSFT based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (3, 'Jonathan Golub', 'UBS', 'Buy', 392.93, '2024-09-02', 'Buy rating for GOOGL based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (3, 'Michael Wilson', 'Morgan Stanley', 'Buy', 417.54, '2024-12-13', 'Buy rating for GOOGL based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (4, 'Michael Wilson', 'Morgan Stanley', 'Buy', 440.97, '2024-11-02', 'Buy rating for NVDA based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (4, 'Savita Subramanian', 'Bank of America', 'Buy', 282.87, '2024-11-27', 'Buy rating for NVDA based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (4, 'Christopher Harvey', 'Wells Fargo', 'Sell', 375.25, '2024-09-11', 'Sell rating for NVDA based on sector outlook.');
INSERT INTO analyst_ratings (company_id, analyst_name, firm, rating, price_target, rating_date, notes) VALUES (5, 'Binky Chadha', 'Deutsche Bank', 'Hold', 367.36, '2024-11-28', 'Hold rating for META based on sector outlook.');

-- NOTE: This file contains only sample rows. For full data, run seed_script.py
